### ISSUE TITLE
Welcome to SEBC!

### ISSUE THREAD

**Issue by mfernest** [louisv1/SEBC#1]
Your repo shows a top-level directory called `SEBC-master`. Your repo should display the contents of this folder, not the folder itself.

Once this matter is corrected, you can remove the `invalid` label from this Issue.

Please invite `rsiwicki` to collaborate on this repo if you have not already. Once he has accepted, you can remove the `incomplete` label as well.

Once both matters have been addressed, you can close this Issue. Good luck this week!

**Comment by louisv1** [comment]
is this correct now?

**Comment by louisv1** [comment]
Think everything is correct now.

Please confirm

Thanks.
