### ISSUE TITLE
 Kerberize cluster 

### ISSUE THREAD

**Issue by louisv1** [louisv1/SEBC#13]
started

**Comment by louisv1** [comment]
-KDC server installed
-Kerberos workstations installed
-tested from all node, working
-wizard run
-done

**Comment by louisv1** [comment]
-terradat running, screen output keeps hanging
-writing results to file

**Comment by louisv1** [comment]
done, submitted

**Comment by mfernest** [comment]
Didn't need the binary files in `/var/kerberos/krb5kdc/`.

**C**omplete.
