### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by louisv1** [louisv1/SEBC#2]
* Created five `m3.xlarge` nodes
* Make sure your AMI is based on a Cloudera-supported OS, using centos 6.5, checked. Supported
* Reserve one instance to host Cloudera Manager server and edge/client-facing services. Architecture will be
-node1 - CM, edge services
-node2 - M1 with DN, NM
-node3 - M2 with DN, NM
-node4 - with DN, NM
-node5 - with DN, NM

**Comment by louisv1** [comment]
**system config checks**
1. Check `vm.swappiness` on all your nodes. 
    -Done, added to /etc/sysctl.conf
2. Show the mount attributes of all volumes. 
    -Only have one drive, didn't add multiple drives.
3. Show the reserve space of any non-root, `ext`-based volumes. 
    -df -h shows all volumes, how much used. Fine
4. Disable transparent hugepage support
    -not on
4. List your network interface configuration
   -left as is in aws, tested lookups and all worked. 
5. List forward and reverse host lookups using `getent` or `nslookup`
  -nslookup ip-172-31-21-180
   Server:         172.31.0.2 
  Address:        172.31.0.2#53

  Non-authoritative answer: 
  Name:   ip-172-31-21-180.eu-west-1.compute.internal
  Address: 172.31.21.180

6. Disable SELinux
7. Disable iptables and ensure it isn't on auto boot

**Comment by louisv1** [comment]
**MySQL install**
-MySQL 5.7 repo installed
-MySQL secure install done
-MySQL install done on Node1 and Node2
-MySQL Java connector on Node1 and Node2, not needed everywhere. Only where service that connects to db
-Ensure MySQL uses innodb

**Comment by louisv1** [comment]
**MySQL Replication**
-setup my.cnf for master
-setup my.cnf for slave
-start slave, etc
-create testdb with test table with one record. Replication happens. SUCCESS!
-create all other db's and set to replicate. Did all possible db's hive, nav, navms, oozie, rman, scm, activity
-Replication of new db's working

**Comment by louisv1** [comment]
**Cloudera Installation**
-Download cm repo and move to /etc/yum.repos.d
-Update to point to 5.8.3
-Install java on Node 1
-install cloudera-manager-daemons cloudera-manager-server
-prepare scm db 
-start cloudera-scm-server, login on web.
-create admin user with sudo and passwordless access on all machines, use this for install on web
-cloudera install jdk and agents fine on all machines
-packages downloaded, distributed, unpacked and activated fine
-host inspector all green
-install core package, set roles, set db param. done
-rename cluster to louisv1
-save pic, done

-DONE!

**Comment by louisv1** [comment]
**Create a local repo**

-Install httpd/tomcat, done
-download relevant software for local, store in http directory
-test that we cans see software at http://34.252.44.118/cdh5.8.3
-update parcels in cm
-save pic, done

-DONE!

**Comment by rsiwicki** [comment]
I think this is good. Also note that you can use dig @nameserver and dig -x for nameresolution tests.

**Comment by mfernest** [comment]
Complete
