### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by louisv1** [louisv1/SEBC#3]
Started with exercise.

**Comment by louisv1** [comment]
tried distcp between aws instance with azure instance. But the distcp gets confused and uses external and internal and fails with conflict.

**Comment by louisv1** [comment]
distcp exercise done, did local copy.

0_replication.md updated with results

**Comment by louisv1** [comment]
**HDFS Lab: Test HDFS performance**

executed for teragen
hadoop  jar /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar teragen -Dmapred.map.tasks=4 -Ddfs.block.size=33554432 107374182 /user/louisv1/terasort-input 

took 2mins, 1sec


executed tersasort
 time hadoop  jar /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar terasort /user/louisv1/terasort-input /user/louisv1/terasort-output

took 7 mins 18 sec

**Comment by louisv1** [comment]
**HDFS Lab: Test HDFS Snapshots**

Did the below
[root@ip-172-31-19-137 ~]# su - hdfs
[hdfs@ip-172-31-19-137 ~]$ hdfs dfs -mkdir /precious
[hdfs@ip-172-31-19-137 ~]$ hdfs dfs -put /SEBC.zip /precious
[hdfs@ip-172-31-19-137 ~]$ hdfs dfsadmin -allowSnapshot /precious
Allowing snaphot on /precious succeeded
[hdfs@ip-172-31-19-137 ~]$ hdfs dfs -createSnapshot /precious  sebc-hdfs-test
Created snapshot /precious/.snapshot/sebc-hdfs-test
[hdfs@ip-172-31-19-137 ~]$ hdfs dfs -rm -r /precious/SEBC.zip
[hdfs@ip-172-31-19-137 ~]$ hdfs dfs -cp /precious/.snapshot/sebc-hdfs-test/SEBC.zip /precious
[hdfs@ip-172-31-19-137 ~]$ hdfs dfs -ls /precious/
Found 1 items
-rw-r--r--   3 hdfs supergroup     415069 2017-03-07 15:21 /precious/SEBC.zip

worked. Used hdfs user cause normal user cant do snapshots

**Comment by louisv1** [comment]
**HDFS Lab: Enable HDFS HA**

-Enabled hdfs ha
-Updated hive metastore namenodes
-Added HttpFS, swiched hue to use
-HDFS HA Done.


-Added user louisv1 with password cloudera
-url: http://34.252.44.118:7180/cmf/login
-User add done

**Comment by mfernest** [comment]
Thorough work. I like the balance of detail and short comments in these Issues.
