### ISSUE TITLE
Resource Management & YARN

### ISSUE THREAD

**Issue by louisv1** [louisv1/SEBC#4]
Started

**Comment by louisv1** [comment]
**YARN/RM Lab: Doing the Math**

-Went through this, done.
-Saved results

**Comment by louisv1** [comment]
**YARN/RM Lab: Static Service Pools**

-Change settings
-restarted cluster
-Done

**Comment by louisv1** [comment]
**YARN/RM Lab: Tuning for YARN**

-Reviewing script

**Comment by mfernest** [comment]
Complete
