### ISSUE TITLE
CM Monitoring Labs

### ISSUE THREAD

**Issue by louisv1** [louisv1/SEBC#5]
starte

**Comment by louisv1** [comment]
**CM Monitoring Lab**

Answered questions.
Updated 0_CM_treasure_hunt.md with answers

**Comment by louisv1** [comment]
**Create a Custom Dashboard**

Created, done, updated pic in repo

**Comment by louisv1** [comment]
**Use the API**

did both, worked fine. Interesting

**Comment by louisv1** [comment]
**Upgrade Cloudera Manager**

Done. Also add extra api calls

**Comment by mfernest** [comment]
The submitted files are a little rough for reading.

**C**omplete
