### ISSUE TITLE
HUE Services & Administration

### ISSUE THREAD

**Issue by louisv1** [louisv1/SEBC#7]
started

**Comment by louisv1** [comment]
**HUE Lab: Authenticate using Linux users/groups**

done, a bit tedious but done.

**Comment by louisv1** [comment]
**HUE Lab: Security or Availability?**

•Integrate Hue and Sentry is done, within Hue you can use sentry
•Install a second Hue instance and load balancer......well I did three hue instances and a load balancer. Done and working

**Comment by louisv1** [comment]
work submitted

**Comment by mfernest** [comment]
HUE admin is a little rough around the edges. Not something you want to have to learn at a client site.

**C**omplete
