### ISSUE TITLE
 Challenges Setup 

### ISSUE THREAD

**Issue by louisv1** [louisv1/SEBC#8]
started challenge

**Comment by louisv1** [comment]
[root@ip-172-31-18-189 ~]# grep 'merengues' /etc/group
merengues:x:501:
[root@ip-172-31-18-189 ~]# grep 'barca' /etc/group
barca:x:500:


[root@ip-172-31-18-189 ~]# grep '2010' /etc/passwd
naymar:x:2010:501::/home/naymar:/bin/bash
[root@ip-172-31-18-189 ~]# grep '2016' /etc/passwd
ronaldo:x:2016:500::/home/ronaldo:/bin/bash

**Comment by mfernest** [comment]
Complete
